spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: iris
  jackson:
    serialization:
      INDENT_OUTPUT: true

de:
  baleipzig:
    iris:
      neuralnetconfig:
        pathTrainingImages: /home/sonny/Bilder/TrainingImages
        pathTestImages: /home/sonny/Bilder/TestImages
        learningRate: 3.
        trainingCycles: 50
        trainingSetSize: 2000
        miniBadgeSize: 25
      languageconfiguration:
        #die erste ist Standard
        languages:
          -
            localeKey: de
            displayName: DE
          -
            localeKey: en
            displayName: EN
      example:
        exampleString: foo
        exampleBoolean: true
        exampleListWithStrings:
          - test1
          - test2
          - test3
        exampleListWithPojo:
          -
            name: foo
            info: fooInfo
          -
            name: foo2
            info: fooInfo2
        exampleMapWithPojo:
          entryOne:
            name: foo
            info: fooInfo
          entryTwo:
            name: foo2
            info: fooInfo2
        exampleMapWithString:
          entryOne: foo
          entryTwo: foo2