spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: iris
  jackson:
    serialization:
      INDENT_OUTPUT: true


de:
  baleipzig:
    iris:
      example:
        exampleString: foo
        exampleBoolean: true
        exampleListWithStrings:
          - test1
          - test2
          - test3
        exampleListWithPojo:
          -
            name: foo
            info: fooInfo
          -
            name: foo2
            info: fooInfo2
        exampleMapWithPojo:
          entryOne:
            name: foo
            info: fooInfo
          entryTwo:
            name: foo2
            info: fooInfo2
        exampleMapWithString:
          entryOne: foo
          entryTwo: foo2